export const GET_COURSES_REQUEST = `GET_COURSES_REQUEST`;
export const GET_COURSES_SUCCESS = `GET_COURSES_SUCCESS`;
export const GET_COURSES_FAIL = `GET_COURSES_FAIL`;
export const GET_LEARNING_PATHS_REQUEST = `GET_LEARNING_PATHS_REQUEST`;
export const GET_LEARNING_PATHS_SUCCESS = `GET_LEARNING_PATHS_SUCCESS`;
export const GET_LEARNING_PATHS_FAIL = `GET_LEARNING_PATHS_FAIL`;
