export const GET_LIST_CART_ITEM_REQUEST = `GET_LIST_CART_ITEM_REQUEST`;
export const GET_LIST_CART_ITEM_SUCCESS = `GET_LIST_CART_ITEM_SUCCESS`;
export const GET_LIST_CART_ITEM_FAILED = `GET_LIST_CART_ITEM_FAILED`;
export const GET_COURSES_REQUEST = `GET_COURSES_REQUEST`;
export const GET_COURSES_SUCCESS = `GET_COURSES_SUCCESS`;
export const GET_COURSES_FAIL = `GET_COURSES_FAIL`;
